## 服务器端口
server:
  port: 8900
## spring配置
spring:
  # 开发工具
  devtools:
    restart:
      pollInterval: 5s
  #MVC
  mvc:
    view:
      prefix: classpath:resources/
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  #数据持久化，需要填写自己的数据库相关信息 ，并在App.java中开启@MapperScan注解
  datasource:
    name: datasource
    url: jdbc:mysql://192.168.128.134/jbill?useUnicode=true&amp;amp;characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 2
    max-idle: 2
    min-idle: 2
    initial-size: 2

## 把数据持久层 mapper文件位置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml